### ISSUE TITLE
first npm install fails

### ISSUE THREAD

**Issue by fgravin** [geosolutions-it/MapStoreExtension#4]
Hi,

With node `12.21.0` (same with later versions)

The first `npm install` emits a lot of errors even though the post install looks successful. If you then run a `npm start` the application does not start.
Actually, you need to perform a second `npm install` to see the dep installation fully successful.

`npm install` logs
```
npm WARN deprecated turf-invariant@3.0.12: Turf packages are now namespaced: please use @turf/invariant instead

> ttf2woff2@2.0.3 install /home/fgravin/dev/MapStoreExtension/node_modules/ttf2woff2
> (node-gyp rebuild > builderror.log) || (exit 0)

../csrc/addon.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE convert(Nan::NAN_METHOD_ARGS_TYPE)’:
../csrc/addon.cc:10:49: error: no matching function for call to ‘v8::Value::ToObject()’
   Local<Object> inputBuffer = info[0]->ToObject();
                                                 ^
In file included from /home/fgravin/.cache/node-gyp/12.21.0/include/node/node.h:67:0,
                 from ../../nan/nan.h:56,
                 from ../csrc/addon.cc:1:
/home/fgravin/.cache/node-gyp/12.21.0/include/node/v8.h:2672:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                            ^~~~~~~~
/home/fgravin/.cache/node-gyp/12.21.0/include/node/v8.h:2672:44: note:   candidate expects 1 argument, 0 provided
In file included from /home/fgravin/.cache/node-gyp/12.21.0/include/node/v8-internal.h:14:0,
                 from /home/fgravin/.cache/node-gyp/12.21.0/include/node/v8.h:27,
                 from /home/fgravin/.cache/node-gyp/12.21.0/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../csrc/addon.cc:1:
/home/fgravin/.cache/node-gyp/12.21.0/include/node/v8.h:2686:31: note: candidate: v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const
                 Local<Object> ToObject(Isolate* isolate) const);
                               ^
/home/fgravin/.cache/node-gyp/12.21.0/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
/home/fgravin/.cache/node-gyp/12.21.0/include/node/v8.h:2686:31: note:   candidate expects 1 argument, 0 provided
                 Local<Object> ToObject(Isolate* isolate) const);
                               ^
/home/fgravin/.cache/node-gyp/12.21.0/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
make: *** [Release/obj.target/addon/csrc/addon.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/fgravin/.nvm/versions/node/v12.21.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 4.15.0-136-generic
gyp ERR! command "/home/fgravin/.nvm/versions/node/v12.21.0/bin/node" "/home/fgravin/.nvm/versions/node/v12.21.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/fgravin/dev/MapStoreExtension/node_modules/ttf2woff2
gyp ERR! node -v v12.21.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 

> core-js@2.6.12 postinstall /home/fgravin/dev/MapStoreExtension/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

```

**Comment by offtherailz** [comment]
This seems a duplication of #7 solved by #5.
Align to master or apply the changes to your project to solve the issue.
